### PR TITLE
Exit with non-zero exit code when a backup error occurs

### PR DESCRIPTION
**Pull request by duckpuppy**

### CODE REVIEW

**Comment by kennyg** [comment]
silly failure

Running RuboCop...
Inspecting 17 files
C................

Offenses:

lib/backupsss.rb:92:81: C: Line is too long. [83/80]
      abort("ERROR - backup failed: #{exc.message}\n#{exc.backtrace.join("\n\t")}")
                                                                                ^^^

17 files inspected, 1 offense detected
RuboCop failed!

bundle exec rake rubocop returned exit code 1

**Comment by jantman** [comment]
This looks good to me aside from the rubocop failure, though I'd ideally like @reppard to take a peek since he knows this code best.

**Comment by reppard** [comment]
ditto @jantman.  @duckpuppy you mind fixing that style issue before we merge this?

**Comment by jantman** [comment]
@duckpuppy Looks like rubocop is still failing on a line that's too long?

**Review by jantman — APPROVED** [review]
Nice work!

**Pull request merged**
